services:
  db:
    image: postgres
    container_name: jewerly_db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'jewerly'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - freecodecamp
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: nest
  #   networks:
  #     - freecodecamp

  # cache:
  # image: redis:latest
  # container_name: cache
  # ports:
  #   - '6390:6379'
  # command: redis-server
  # volumes:
  #   - cache:/data

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: jewerly
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:root@host.docker.internal:5434/jewerly
    command: yarn start:dev
    ports:
      - '4000:4000'
    # command: npx prisma migrate dev --name dev-mig && npx prisma generate && npx prisma generate --schema=prisma_sqlite/schema.prisma
    depends_on:
      - db
      # - cache
networks:
  freecodecamp:
volumes:
  # cache:
  postgres:
